create table if not exists airbnb.public.stg_listings (
    id bigint not null,
    listing_url text,
    scrape_id bigint not null,
    last_scraped date,
    source text, -- 'city scrape', 'previous scrape'
    name text,
    description text,
    neighborhood_overview text,
    picture_url text,
    host_id bigint not null,
    host_url text,
    host_name text,
    host_since date,
    host_location text,
    host_about text,
    host_response_time text, -- 'within an hour', 'within a few hours', 'within a day', 'a few days or more' -- noqa
    host_response_rate real,
    host_acceptance_rate real,
    host_is_superhost boolean,
    host_thumbnail_url text,
    host_picture_url text,
    host_neighbourhood text,
    host_listings_count integer,
    host_total_listings_count integer,
    host_verifications text [], -- 'email', 'phone', 'work_email'
    host_has_profile_pic boolean,
    host_identity_verified boolean,
    neighbourhood text,
    neighbourhood_cleansed text,
    neighbourhood_group_cleansed text,
    latitude real,
    longitude real,
    property_type text, -- 'Entire home/apt', 'Private room', 'Shared room', 'Hotel room' -- noqa
    room_type text,
    accommodates integer,
    bathrooms integer,
    bathrooms_text text,
    bedrooms integer,
    beds integer,
    amenities text,
    price real,
    minimum_nights integer,
    maximum_nights integer,
    minimum_minimum_nights integer,
    maximum_minimum_nights integer,
    minimum_maximum_nights integer,
    maximum_maximum_nights integer,
    minimum_nights_avg_ntm real,
    maximum_nights_avg_ntm real,
    calendar_updated date,
    has_availability boolean,
    availability_30 integer,
    availability_60 integer,
    availability_90 integer,
    availability_365 integer,
    calendar_last_scraped date,
    number_of_reviews integer,
    number_of_reviews_ltm integer,
    number_of_reviews_l30d integer,
    first_review date,
    last_review date,
    review_scores_rating real,
    review_scores_accuracy real,
    review_scores_cleanliness real,
    review_scores_checkin real,
    review_scores_communication real,
    review_scores_location real,
    review_scores_value real,
    license text,
    instant_bookable boolean,
    calculated_host_listings_count int,
    calculated_host_listings_count_entire_homes int,
    calculated_host_listings_count_private_rooms int,
    calculated_host_listings_count_shared_rooms int,
    reviews_per_month real
);
